---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian9}-ansible:latest"
    pre_build_image: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    exposed_ports:
    - 8080/tcp
    - 8983/tcp
    published_ports:
    - 0.0.0.0:8080:8080/tcp
    - 0.0.0.0:8983:8983/tcp
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
